version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres_fast_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    command: >
      bash -c "alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data: