"""Updated note model

Revision ID: a1832a0c1402
Revises: e4baeda20808
Create Date: 2024-08-30 17:46:45.422705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1832a0c1402"
down_revision: Union[str, None] = "e4baeda20808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notes", "author_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notes", "author_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
