"""Initial revision

Revision ID: e4baeda20808
Revises: 9a00709b77ad
Create Date: 2024-08-30 13:57:30.263661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4baeda20808"
down_revision: Union[str, None] = "9a00709b77ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notes", "description", existing_type=sa.TEXT(), nullable=True)
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "is_user", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_super_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.drop_column("users", "is_super_admin")
    op.drop_column("users", "is_user")
    op.drop_column("users", "password")
    op.alter_column("notes", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
